Created Argparse user method.
stfc/SCD-OpenStack-Utils pull request #106
Opened 2023-10-20 09:27 UTC by khalford

This method allows a user to run a python script from the terminal with parameters to upload data from a csv into Netbox. There are lib code changes as the code hasn't been tested with a Netbox connection in a while.

2023-10-20 12:26 UTC, meoflynn requested changes

2023-10-20 12:26 UTC, meoflynn commented on Pynetbox_Data_Uploader/lib/utils/format_dict.py
> +        This method iterates through each dictionary and calls a format method on each.
Could you include `:param dicts:` to the docstring?

2023-10-20 12:26 UTC, meoflynn commented on Pynetbox_Data_Uploader/lib/user_methods/csv_to_netbox.py
> +        This will take the csv file and return a list of device dictionaries.
Could you add `:param file_path:` to the docstring

2023-10-30 08:57 UTC, meoflynn approved these changes

2023-10-30 09:17 UTC, Protabs approved these changes

2023-10-30 09:17 UTC, merged