Add logging to note were clearing existing records
stfc/SCD-OpenStack-Utils pull request #107
Opened 2023-10-26 08:51 UTC by DavidFair

Adds some extra logging, to just say why we're removing a VM during a creation as it might not be obvious

2023-10-26 08:52 UTC, meoflynn approved these changes

2023-10-26 08:54 UTC, anish-mudaraddi approved these changes

2023-10-30 11:04 UTC, anish-mudaraddi requested changes
looks like your pylint is failing

2023-11-23 09:47 UTC, anish-mudaraddi approved these changes

2023-11-23 09:47 UTC, merged