ENH - rewrite rally_extract_tests.py
stfc/SCD-OpenStack-Utils pull request #137
Opened 2024-04-22 13:33 UTC by anish-mudaraddi

rewrite rally_extract_tests.py incorporating changes from #89 
Needs unit-tests and proper testing

2024-06-06 08:35 UTC, khalford requested changes

2024-06-06 08:35 UTC, khalford commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +def build_datastring(metrics: List, instance: str):
```suggestion
def build_datastring(metrics: List, instance: str) -> str:
```

2024-06-06 08:35 UTC, khalford commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +def rally_extract_results(report_path: Path, config_path: Path):
```suggestion
def rally_extract_results(report_path: Path, config_path: Path) -> None:
```

2024-06-06 08:35 UTC, khalford commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +        success_flag = int(all(sla["success"] for sla in test_entry["sla"]))
```suggestion
    if test_entry["sla"]:
        temp_list = [sla["success"] for sla in test_entry["sla"]]
        success_flag = int(all(temp_list))
```

2024-06-06 08:35 UTC, khalford commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +    ), "Config file is missing required values."
Do we want to error with which values we are missing here?

2024-06-06 08:35 UTC, khalford commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +
```suggestion
    check_args(args)
    rally_extract_results(args.rally_filepath, config_path)

def check_args(args;  argparse.parser) -> None:
    try:
        args = parser.parse_args(user_args)
    except argparse.ArgumentTypeError as exp:
        raise RuntimeError("Error reading input arguments") from exp

    if not args.rally_filepath.is_file():
        raise RuntimeError(f"Invalid filepath given '{args.config_filepath}'")

    try:
        read_config_file(config_path)
    except configparser.Error as exp:
        raise RuntimeError(
            f"could not read influx db config file '{args.config_filepath}'"
        ) from exp


```

2024-06-06 08:35 UTC, khalford commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +
Moving the arg checking outside of main.

2024-06-17 12:16 UTC, meoflynn requested changes

2024-06-24 14:43 UTC, anish-mudaraddi commented on OpenStack-Rally-Tester/usr/local/bin/rally_extract_results.py
> +def main(user_args: List):
no it doesn't return anything - it just writes rally test results to a file

2024-06-24 14:46 UTC, anish-mudaraddi commented
I'm still waiting for when Ops is not busy so I can grab some dummy rally output files to use for testing

2024-09-30 09:24 UTC, anish-mudaraddi commented
I'm closing this until I write the tests

2024-09-30 09:24 UTC, closed without merging