Added CodeQL for codescanning.
stfc/SCD-OpenStack-Utils pull request #139
Opened 2024-05-28 10:15 UTC by RWhiting78

Added CodeQL workflows to the repository.

2024-05-28 12:18 UTC, khalford approved these changes

2024-05-31 09:05 UTC, khalford requested changes

2024-05-31 09:05 UTC, khalford commented on .github/workflows/codeql.yml
> +    - cron: '17 23 * * 4'
```suggestion
    - cron: '23 12 * * 3'
```
Suggestion made by David on st2-cloud-pack. Should change it here too.

2024-06-07 12:47 UTC, khalford approved these changes

2024-06-07 14:59 UTC, anish-mudaraddi approved these changes

2024-06-07 14:59 UTC, merged