Cloud chatops refactor
stfc/SCD-OpenStack-Utils pull request #140
Opened 2024-05-28 10:18 UTC by khalford

This PR adds the Cloud ChatOps application which is unfinished.

2024-05-28 14:10 UTC, RWhiting78 submitted a review, later dismissed

2024-06-07 14:23 UTC, anish-mudaraddi requested changes
Here are some suggestions of how I would refactor your code to make it more extensible.

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/get_github_prs.py
> +    def get_http_response(self, url: str) -> List[Dict]:
This class is getting too big imo - you have a lot of public methods here that aren't directly related to getting GitHub repos and can be moved to a more generic "Handler" Class. 

We want to make the class have a single responsibility so its easier to debug

Here's how I would go about this:

`GetGitHubPRs` - should have one publicly facing function called `run` - it's responsibility should be associated with getting repos from GitHub

Create a class like `HTTPHandler` with this `get_http_response` as the publicly facing function - its responsibility is handling http responses.  This class should be instantiated and used by `GetGitHubPRs` class (known as composition in OOP)

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/get_github_prs.py
> +    def remove_empty_response(
this method should be private

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/get_github_prs.py
> +    def validate_response(response: requests.get, url: str) -> None:
this method should be private

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/pr_reminder.py
> +                info = {
if we set `GetGitHubPRs.run()` to output a list of dataclasses with the information already parsed into the way we want we could potentially remove the need for this

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/pr_reminder.py
> +        self.prs = GetGitHubPRs(get_repos(), "stfc").run()
To make this easier - we could potentially have`GetGitHubPRs.run()` return a list of dataclasses - where each dataclass contains information about a PR

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/pr_reminder.py
> +    def run(self, mention, channel=None) -> None:
this should be the only public facing method in the class - all others should be private since they should only be used internally

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/pr_reminder.py
> +    def run(self, mention, channel=None) -> None:
Rule of thumb is if you want to integrate this class into other automation code - what methods should make up the API and what should we not let other code outside the class access

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/pr_reminder.py
> +    def check_pr(self, info: Dict) -> Dict:
this class is also getting too big - you have this doing 2 things, validating the PR and posting it - which should be two separate classes same as above

2024-06-07 14:23 UTC, anish-mudaraddi commented on cloud_chatops/src/pr_reminder.py
> +    def check_pr(self, info: Dict) -> Dict:
You should break the class up into 

`PRMessageBuilder` - which checks various collected PRs, validates and builds a message to send
`PRMessagePoster` - which takes a list of PR messages and posts them as a single slack message.

2024-06-11 12:30 UTC, anish-mudaraddi approved these changes

2024-06-11 13:18 UTC, merged