Add monitoring tools from utils node
stfc/SCD-OpenStack-Utils pull request #22
Opened 2021-02-02 16:26 UTC by apdibbo

Adds a script which calculates the number of instances of each flavor can be created
Openstack service status into influx
QUota changes into influx

2023-02-21 11:11 UTC, DavidFair requested changes
Partial review

2023-02-21 11:11 UTC, DavidFair commented on MonitoringTools/usr/local/bin/limits-to-influx.py
> +   print 'Unable to read from config file'
This file needs `2to3` treatment too

2023-02-21 11:11 UTC, DavidFair commented on MonitoringTools/usr/local/bin/slottifier.py
> +env = os.environ.copy()
Duplicated LOC

2023-02-21 11:11 UTC, DavidFair commented on MonitoringTools/usr/local/bin/slottifier.py
> +url = 'http://'+host+'/write?db='+database +'&precision=s'
We have these LOC 4 times across multiple files, IMO this is worth moving into another file and have the other scripts import it so we only have to change it once

2023-02-21 11:42 UTC, apdibbo commented
How does one 2to3?

2023-02-21 15:13 UTC, apdibbo commented
I am actually going to make another quick change to this

2024-02-02 10:01 UTC, anish-mudaraddi commented
see #127 for refactored version of this code

2024-02-02 10:01 UTC, closed without merging